# Generated by Django 4.2.4 on 2023-08-21 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bus_flight_hotel_rentalcar_route_delete_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='book_hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.hotel'),
        ),
        migrations.AddField(
            model_name='flight',
            name='rent_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.rentalcar'),
        ),
    ]
