# Generated by Django 4.2.4 on 2023-08-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_flight_book_hotel_flight_rent_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='traveler_name',
            field=models.CharField(default='NEW', max_length=20),
        ),
    ]
