# Generated by Django 4.2.4 on 2023-08-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bus_traveler_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
