# Generated by Django 4.2.4 on 2023-08-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_flight_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='rentalcar',
            name='image',
            field=models.ImageField(null=True, upload_to='destinations/'),
        ),
    ]
