# Generated by Django 4.2.4 on 2023-08-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_hotel_image_alter_rentalcar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
