# Generated by Django 4.2.4 on 2023-08-27 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
